const digitsConfig = {
  min: 1, // minimum value for each digit (assuming inclusive)
  max: 49, // max value for each digit (assuming inclusive)
  minCount: 6, // minimum number of digits that can be generated by UI
  maxCount: 7, // minimum number of digits that can be generated by UI
  defaultCount: 6, // default count for the number of digits
  colors: [
    {
      min: 1, // range minimum
      max: 9, // range maximum
      color: "#808080", // grey
    },
    {
      min: 10,
      max: 19,
      color: "#0000FF", // blue
    },
    {
      min: 20,
      max: 29,
      color: "#FFC0CB", // pink
    },
    {
      min: 30,
      max: 39,
      color: "#008000", // green
    },
    {
      min: 40,
      max: 49,
      color: "#FFFF00", // yellow
    },
  ],
};

export default digitsConfig;
